# Generated by Django 4.0.3 on 2022-05-14 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lieu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_place', models.CharField(max_length=255)),
                ('categories', models.CharField(choices=[('restaurant', 'Restaurant'), ('hotel', 'Hotel'), ('cinema', 'Cinema'), ('parc', 'Parc'), ('plage', 'Plage'), ('centre Commercial', 'Centre Commercial'), ('jardin', 'Jardin'), ('centre culturel', 'Centre Culturel'), ('bibliotheque', 'Bibliothèque'), ('théatre', 'Théatre'), ('musée', 'Musée')], max_length=255)),
                ('adress', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='lieu_image')),
            ],
        ),
    ]
