# Generated by Django 4.0.3 on 2022-05-14 23:32

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_users_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personne', models.CharField(default=True, max_length=255, verbose_name=django.contrib.auth.models.User)),
                ('preference', models.CharField(max_length=255)),
                ('lieu_pref', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mysite.lieu')),
            ],
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
