# Generated by Django 4.0.3 on 2022-05-15 00:25

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_preference_delete_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='preference',
            name='personne',
            field=models.CharField(default=True, max_length=254, verbose_name=django.contrib.auth.models.User),
        ),
        migrations.AlterField(
            model_name='preference',
            name='preference',
            field=models.CharField(max_length=254),
        ),
    ]
