# Generated by Django 4.0.3 on 2022-05-19 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mysite', '0004_contact_alter_preference_personne_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preference',
            name='lieu_pref',
        ),
        migrations.RemoveField(
            model_name='preference',
            name='personne',
        ),
        migrations.AddField(
            model_name='preference',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
